### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by timmh** [choyingw/GAIS-Net#1]
The training script [references](https://github.com/choyingw/GAIS-Net/blob/main/tools/train_net.py#L86-L93) two weight files, `mask_pretrain_sur_2.pth` and `miou_pretrain_sur.pth`. I am however unable to find both files. Would you mind sharing them or pointing me into a direction where I can find them? Best regards

**Comment by choyingw** [comment]
Thank you for your interest in this work.

Here are other pretrained models for if you may want to retrain the whole pipeline. 
https://drive.google.com/file/d/1p0ctLVrm8PNBV7O9B3a0mYNmKyw7Hpx4/view?usp=sharing
https://drive.google.com/file/d/166GrAfQTZvVJqevQARheTnd9uWRFkppv/view?usp=sharing

**Comment by timmh** [comment]
Thank you for the quick response! I guess you don't have the `miou_pretrain.pth` or `miou_pretrain_sur_2.pth` files available as well?

**Comment by choyingw** [comment]
Sorry I put the wrong links in the last comment. I just edited the links. They are miou_pretrain_sur.pth/ mask_pretrain_sur_2.pth and should be compatible with the training codes.

**Comment by timmh** [comment]
Thanks a lot!
